openapi: 3.1.0
info:
  version: 1.0.0
  title: Contact app
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  description: This is a documentation of contacts app
#tags:

servers:
  - url: http://localhost:3000
  - url: https://contacts-q6x3.onrender.com
paths:
  /contacts:
    get:
      $ref: ./paths/contacts/get.yaml
    post:
      $ref: ./paths/contacts/post.yaml
  /contacts/{contactId}:
    get:
      $ref: ./paths/contacts/{contactId}/get.yaml

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
